import { PERMISSIONS } from './permissions.js';

const allPermissions = Object.values(PERMISSIONS);

const createExactPreset = (allowedPermissions) => Object.fromEntries(
  allPermissions.map((permission) => [permission, allowedPermissions.includes(permission)])
);

// This is a reviewable UI preset. It is persisted only after the owner confirms a save.
export const MULTIMEDIA_COMPLETE_PRESET = Object.freeze(createExactPreset([
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.EVENTS_VIEW,
  PERMISSIONS.SETLISTS_VIEW,
  PERMISSIONS.SETLISTS_ADD_SONG,
  PERMISSIONS.SETLISTS_REMOVE_SONG,
  PERMISSIONS.SETLISTS_REORDER,
  PERMISSIONS.SETLISTS_CONTROL,
  PERMISSIONS.SONGS_VIEW,
  PERMISSIONS.SONGS_CREATE,
  PERMISSIONS.SONGS_EDIT_LYRICS,
  PERMISSIONS.SONGS_EDIT_CHORDS,
  PERMISSIONS.SONGS_EDIT_METADATA,
  PERMISSIONS.SONGS_MANAGE_MEDIA,
  PERMISSIONS.SONGS_ARCHIVE,
  PERMISSIONS.REHEARSAL_ACCESS,
  PERMISSIONS.REHEARSAL_CONTROL,
  PERMISSIONS.BIBLE_VIEW,
  PERMISSIONS.BIBLE_PROJECT,
  PERMISSIONS.BIBLE_QUICK_PROJECTION,
  PERMISSIONS.SERMONS_VIEW,
  PERMISSIONS.SERMONS_CREATE,
  PERMISSIONS.SERMONS_EDIT,
  PERMISSIONS.SERMONS_PROJECT,
  PERMISSIONS.MULTIMEDIA_LIBRARY_VIEW,
  PERMISSIONS.MULTIMEDIA_UPLOAD,
  PERMISSIONS.MULTIMEDIA_EDIT,
  PERMISSIONS.MULTIMEDIA_CENTRAL_ACCESS,
  PERMISSIONS.MULTIMEDIA_CONTROL_OUTPUTS,
  PERMISSIONS.MULTIMEDIA_PROJECT,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_PROJECT,
  PERMISSIONS.PROFILE_EDIT_OWN
]));

// A non-destructive group preset: only these explicit overrides are applied.
export const MULTIMEDIA_SUPPORT_PRESET = Object.freeze({
  [PERMISSIONS.EVENTS_VIEW]: true,
  [PERMISSIONS.SETLISTS_VIEW]: true,
  [PERMISSIONS.SETLISTS_ADD_SONG]: true,
  [PERMISSIONS.BIBLE_VIEW]: true,
  [PERMISSIONS.BIBLE_PROJECT]: true,
  [PERMISSIONS.BIBLE_QUICK_PROJECTION]: true,
  [PERMISSIONS.MULTIMEDIA_CENTRAL_ACCESS]: true,
  [PERMISSIONS.MULTIMEDIA_PROJECT]: true,
  [PERMISSIONS.ANNOUNCEMENTS_VIEW]: true,
  [PERMISSIONS.ANNOUNCEMENTS_PROJECT]: true
});

export const GROUP_PERMISSION_PRESETS = Object.freeze({
  multimediaComplete: MULTIMEDIA_COMPLETE_PRESET,
  multimediaSupport: MULTIMEDIA_SUPPORT_PRESET
});
