import { PERMISSIONS } from './permissions.js';

const allPermissions = Object.values(PERMISSIONS);

const createExactPreset = (allowedPermissions) => Object.fromEntries(
  allPermissions.map((permission) => [permission, allowedPermissions.includes(permission)])
);

// This is a reviewable UI preset. It is persisted only after the owner confirms a save.
export const MULTIMEDIA_COMPLETE_PRESET = Object.freeze(createExactPreset([
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.EVENTS_VIEW,
  PERMISSIONS.SETLISTS_VIEW,
  PERMISSIONS.SETLISTS_ADD_SONG,
  PERMISSIONS.SETLISTS_REMOVE_SONG,
  PERMISSIONS.SETLISTS_REORDER,
  PERMISSIONS.SETLISTS_CONTROL,
  PERMISSIONS.SETLISTS_MANAGE,
  PERMISSIONS.SONGS_VIEW,
  PERMISSIONS.SONGS_CREATE,
  PERMISSIONS.SONGS_EDIT_LYRICS,
  PERMISSIONS.SONGS_EDIT_CHORDS,
  PERMISSIONS.SONGS_EDIT_METADATA,
  PERMISSIONS.SONGS_MANAGE_MEDIA,
  PERMISSIONS.SONGS_ARCHIVE,
  PERMISSIONS.REHEARSAL_ACCESS,
  PERMISSIONS.REHEARSAL_CONTROL,
  PERMISSIONS.BIBLE_VIEW,
  PERMISSIONS.BIBLE_PROJECT,
  PERMISSIONS.BIBLE_QUICK_PROJECTION,
  PERMISSIONS.SERMONS_VIEW,
  PERMISSIONS.SERMONS_CREATE,
  PERMISSIONS.SERMONS_EDIT,
  PERMISSIONS.SERMONS_CREATE_POINT,
  PERMISSIONS.SERMONS_CREATE_BIBLE_PASSAGE,
  PERMISSIONS.SERMONS_PROJECT,
  PERMISSIONS.MULTIMEDIA_LIBRARY_VIEW,
  PERMISSIONS.MULTIMEDIA_UPLOAD,
  PERMISSIONS.MULTIMEDIA_EDIT,
  PERMISSIONS.MULTIMEDIA_DELETE,
  PERMISSIONS.MULTIMEDIA_CENTRAL_ACCESS,
  PERMISSIONS.MULTIMEDIA_CONTROL_OUTPUTS,
  PERMISSIONS.MULTIMEDIA_PROJECT,
  PERMISSIONS.CANVA_VIEW,
  PERMISSIONS.CANVA_CREATE,
  PERMISSIONS.CANVA_EDIT,
  PERMISSIONS.CANVA_DELETE,
  PERMISSIONS.CANVA_PROJECT,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_PROJECT,
  PERMISSIONS.PROFILE_EDIT_OWN
]));

// Operación TOTAL para el equipo Multimedia.
// Incluye todo el flujo operativo y destructivo de contenido Multimedia/Canva/Anuncios,
// proyección de canciones, Biblia y prédica. No entrega administración de roles/permisos ni Devocionales reservados.
export const MULTIMEDIA_TOTAL_PRESET = Object.freeze({
  [PERMISSIONS.DASHBOARD_VIEW]: true,
  [PERMISSIONS.EVENTS_VIEW]: true,
  [PERMISSIONS.EVENTS_EDIT]: true,
  [PERMISSIONS.SETLISTS_VIEW]: true,
  [PERMISSIONS.SETLISTS_ADD_SONG]: true,
  [PERMISSIONS.SETLISTS_REMOVE_SONG]: true,
  [PERMISSIONS.SETLISTS_REORDER]: true,
  [PERMISSIONS.SETLISTS_CONTROL]: true,
  [PERMISSIONS.SETLISTS_MANAGE]: true,
  [PERMISSIONS.SONGS_VIEW]: true,
  [PERMISSIONS.SONGS_CREATE]: true,
  [PERMISSIONS.SONGS_EDIT_LYRICS]: true,
  [PERMISSIONS.SONGS_EDIT_CHORDS]: true,
  [PERMISSIONS.SONGS_EDIT_METADATA]: true,
  [PERMISSIONS.SONGS_MANAGE_MEDIA]: true,
  [PERMISSIONS.SONGS_ARCHIVE]: true,
  [PERMISSIONS.REHEARSAL_ACCESS]: true,
  [PERMISSIONS.REHEARSAL_CONTROL]: true,
  [PERMISSIONS.BIBLE_VIEW]: true,
  [PERMISSIONS.BIBLE_PROJECT]: true,
  [PERMISSIONS.BIBLE_QUICK_PROJECTION]: true,
  [PERMISSIONS.SERMONS_VIEW]: true,
  [PERMISSIONS.SERMONS_CREATE]: true,
  [PERMISSIONS.SERMONS_EDIT]: true,
  [PERMISSIONS.SERMONS_CREATE_POINT]: true,
  [PERMISSIONS.SERMONS_CREATE_BIBLE_PASSAGE]: true,
  [PERMISSIONS.SERMONS_PROJECT]: true,
  [PERMISSIONS.MULTIMEDIA_LIBRARY_VIEW]: true,
  [PERMISSIONS.MULTIMEDIA_UPLOAD]: true,
  [PERMISSIONS.MULTIMEDIA_EDIT]: true,
  [PERMISSIONS.MULTIMEDIA_DELETE]: true,
  [PERMISSIONS.MULTIMEDIA_CENTRAL_ACCESS]: true,
  [PERMISSIONS.MULTIMEDIA_CONTROL_OUTPUTS]: true,
  [PERMISSIONS.MULTIMEDIA_PROJECT]: true,
  [PERMISSIONS.CANVA_VIEW]: true,
  [PERMISSIONS.CANVA_CREATE]: true,
  [PERMISSIONS.CANVA_EDIT]: true,
  [PERMISSIONS.CANVA_DELETE]: true,
  [PERMISSIONS.CANVA_PROJECT]: true,
  [PERMISSIONS.ANNOUNCEMENTS_VIEW]: true,
  [PERMISSIONS.ANNOUNCEMENTS_CREATE]: true,
  [PERMISSIONS.ANNOUNCEMENTS_EDIT]: true,
  [PERMISSIONS.ANNOUNCEMENTS_DELETE]: true,
  [PERMISSIONS.ANNOUNCEMENTS_PROJECT]: true,
  [PERMISSIONS.TEAM_VIEW]: true,
  [PERMISSIONS.PROFILE_EDIT_OWN]: true,
});

// A non-destructive group preset: only these explicit overrides are applied.
export const MULTIMEDIA_SUPPORT_PRESET = Object.freeze({
  [PERMISSIONS.EVENTS_VIEW]: true,
  [PERMISSIONS.SETLISTS_VIEW]: true,
  [PERMISSIONS.SETLISTS_ADD_SONG]: true,
  [PERMISSIONS.BIBLE_VIEW]: true,
  [PERMISSIONS.BIBLE_PROJECT]: true,
  [PERMISSIONS.BIBLE_QUICK_PROJECTION]: true,
  [PERMISSIONS.MULTIMEDIA_CENTRAL_ACCESS]: true,
  [PERMISSIONS.MULTIMEDIA_PROJECT]: true,
  [PERMISSIONS.CANVA_VIEW]: true,
  [PERMISSIONS.CANVA_PROJECT]: true,
  [PERMISSIONS.ANNOUNCEMENTS_VIEW]: true,
  [PERMISSIONS.ANNOUNCEMENTS_PROJECT]: true
});

export const GROUP_PERMISSION_PRESETS = Object.freeze({
  multimediaTotal: MULTIMEDIA_TOTAL_PRESET,
  multimediaComplete: MULTIMEDIA_COMPLETE_PRESET,
  multimediaSupport: MULTIMEDIA_SUPPORT_PRESET
});
